FROM eclipse-temurin:17.0.6_10-jdk-alpine as step1
WORKDIR /app
COPY . .
RUN .\mvnw package

FROM eclipse-temurin:17.0.6_10-jre-alpine
WORKDIR /abc
COPY --from=step1 /app/target/demo.jar ./demo2.jar
CMD ["java", "-jar", "demo2.jar"]
